Fix: Benchmark errors
Berkmann18/NativeVsUtils pull request #5
Opened 2021-05-14 10:55 UTC by victor-homyakov

## Checklist

-   [x] The PR follows the [guidelines](CONTRIBUTING.md)
-   [x] Passes all the tests (including added/updated ones)
-   [x] Contains a valid documentation
-   [x] It's not a duplicate from another PR

## Changes
This PR implements:
-   [x] Bugfix
-   [ ] Feature
-   [ ] Refactoring
-   [ ] Documentation/wiki/tutorial update
-   [ ] Code style update
-   [ ] Build related change
-   [ ] Other, please specify:

## Details
What does this PR implements exactly?
- removed references to `__`, because there is no Underscore (`__` is undefined)
- fixed incorrect invocation of native `reduce` and `reduceRight`
- fixed missing local variable `x`
- fixed incorrect invocation of `_.replace`

What issues does this resolve?

If it completes one or more tasks (listed in [TODO](TODO.md)), which ones are those?

2021-05-14 19:18 UTC, Berkmann18 requested changes

2021-05-14 19:18 UTC, Berkmann18 commented on nativeVsLodash.js
> -  .add('underscore', () => __.concat(a0, 2, [3], [
It's true that there weren't any definition of `__` which should have been the case, so this doesn't need to be removed.

2021-05-14 19:18 UTC, Berkmann18 commented on nativeVsLodash.js
> +  .add('native', () => a1.reduce(redux))
Thanks for catching that and the rest 😁.

2021-05-14 19:21 UTC, Berkmann18 approved these changes

2021-05-14 19:23 UTC, merged

2021-05-14 19:28 UTC, Berkmann18 commented
Would you be okay if I add you to the All Contributors table (not pushed yet)?

2021-05-15 11:41 UTC, victor-homyakov commented
> Would it be okay if I add you to the All Contributors table?

OK